instances:

- name: worker

  gce_machine_type: e2-micro

  gce_source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-l$

  gce_zone: europe-west1-b 

  gce_project: CNP-QSI



admin_username: admin

admin_ssh_key: ....