- name: Apt update
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt update

- name: Install iperf
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt install -y iperf

- name: Install iperf3
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt install -y iperf3

- name: Install iperf3
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt install -y iperf3

- name: Install pip
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt install -y python3-pip

- name: Install ntp 
  become: yes
  ansible.builtin.shell:
    cmd: sudo apt install -y ntp

- name: Setup /etc/ntp.conf file
  become: true 
  copy:
    src: ntp.conf
    dest:  /etc/ntp.conf

- name: Download owd-tool
  become: true 
  copy:
    src: ../owd-tool/main.py
    dest: /home/runlo