instances:

- name: dummy1

  gce_machine_type: e2-micro

  gce_source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts

  gce_zone:  us-west1-a 

  gce_project: cnp-qsi 

admin_username: admin

admin_ssh_key: "{{ lookup('file', '/Users/runlo/.ssh/id_rsa.pub') }}"

service_account_contents: "{{ lookup('file', 'cred.json') }}"