- name: Create instance
  google.cloud.gcp_compute_instance:

    name: "{{ instances[0].name }}"

    machine_type: "{{ instances[0].gce_machine_type}}"

    disks:

    - auto_delete: true

      boot: true

      initialize_params:

          source_image: "{{instances[0].gce_source_image}}"

    network_interfaces:
    - network: 
        name: "projects/{{instances[0].gce_project}}/global/networks/network"
      access_configs:
      - name: "External NAT"
        type: "ONE_TO_ONE_NAT"

    metadata:

      managed-by: "Ansible"

      ssh-keys: ":\n"

    zone: "{{instances[0].gce_zone}}"

    project: "{{instances[0].gce_project}}"

    auth_kind: serviceaccount

    service_account_contents: "{{service_account_contents}}"

    state: present

    status: RUNNING

- name: Install iperf3
  ansible.builtin.apt:
    name: iperf3

