- name: Create firewall rules
  google.cloud.gcp_compute_firewall:
    name: firewall-rules
    allowed:
    - ip_protocol:  tcp
    - ip_protocol:  udp
    - ip_protocol:  icmp
    source_ranges:
    - 0.0.0.0/0
    target_tags:
    - tg-instance
    project: "{{instances[0].gce_project}}"
    auth_kind: serviceaccount
    service_account_contents: "{{service_account_contents}}"
    state: present


- name: Create instance
  google.cloud.gcp_compute_instance:

    name: "{{instances[0].gce_zone}}-instance"

    machine_type: "{{ instances[0].gce_machine_type}}"

    tags:
      items:
        - tg-instance

    disks:

    - auto_delete: true

      boot: true

      initialize_params:

          source_image: "{{instances[0].gce_source_image}}"

    network_interfaces:
    - network: 
        name: "projects/{{instances[0].gce_project}}/global/networks/network"
      access_configs:
      - name: "External NAT"
        type: "ONE_TO_ONE_NAT"

    metadata:

      managed-by: "Ansible"

      ssh-keys: "runlo:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDh3Cz4FDX7df3bVWGzJlsHynwbMPUHQhzeg0NMXIW6N869coZpwOG037t6F9eZ1/EgIBqRC00ZO++QBAl2x5F8nakPBi8NdPktj64sAYlD5TJFGLanoah8oZq6iqmC5xlYWo19EAO66l3pjirWsQE5nCu5rVRsKo5NibQD+24+Kpc3lRwjcfSRDp4iT+19QATYnspLGDQQlnk5tdrllEJcSzm/s4RIHREtuFGPsEt1SqFVsU2FBY+KciuX0owDeU8lMvAwxN2F39ytlB0yNurw+kJ1FmaLHyexDdiHYeiTKWSsyQwD6I+eUGT8q8+9NziMQ9sn1l3JiWUNFGSGnlj+FRoJ8ZDmpRknQSPC2uQVG6jRNZVvj57lQvHMqlUJogUQ/p5HNI5OjoCtobb4hWMaTFO+lHUv5T3OpULcjpFv1LCCd5RaTHOpVLKZHCFRUFNZn7xx1WEtmgqBItKJbXem8Ws1qGH1Uu/nQ+80hL0vBKuCjFJjUjz/aakgn8GPnE8= runlo@Goncalos-MacBook-Air-5.local"

    zone: "{{instances[0].gce_zone}}"

    project: "{{instances[0].gce_project}}"

    auth_kind: serviceaccount

    service_account_contents: "{{service_account_contents}}"

    state: present

    status: RUNNING

  register: result

- name: Wait for SSH to become available
  wait_for:
    host: "{{ result.networkInterfaces[0].accessConfigs[0].natIP }}"
    port: 22
    timeout: 300
  become: no

- name: Add GCP instance to inventory
  add_host:
    name: "{{instances[0].gce_zone}}-instance"
    ansible_host: "{{ result.networkInterfaces[0].accessConfigs[0].natIP }}"
    ansible_user: runlo
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3






