- name: Create firewall rules
  google.cloud.gcp_compute_firewall:
    name: firewall-rules
    allowed:
    - ip_protocol:  tcp
    - ip_protocol:  udp
    - ip_protocol:  icmp
    source_ranges:
    - 0.0.0.0/0
    target_tags:
    - tg-instance
    project: "{{instances[0].gce_project}}"
    auth_kind: serviceaccount
    service_account_contents: "{{service_account_contents}}"
    state: present


- name: Create instance
  google.cloud.gcp_compute_instance:

    name: "{{instances[0].gce_zone}}-instance"

    machine_type: "{{ instances[0].gce_machine_type}}"

    tags:
      items:
        - tg-instance

    disks:

    - auto_delete: true

      boot: true

      initialize_params:

          source_image: "{{instances[0].gce_source_image}}"

    network_interfaces:
    - network: 
        name: "projects/{{instances[0].gce_project}}/global/networks/network"
      access_configs:
      - name: "External NAT"
        type: "ONE_TO_ONE_NAT"

    metadata:

      managed-by: "Ansible"

      ssh-keys: ":\n"

    zone: "{{instances[0].gce_zone}}"

    project: "{{instances[0].gce_project}}"

    auth_kind: serviceaccount

    service_account_contents: "{{service_account_contents}}"

    state: present

    status: RUNNING

  register: result

- name: Wait for SSH to become available
  wait_for:
    host: "{{ result.networkInterfaces[0].accessConfigs[0].natIP }}"
    port: 22
    timeout: 300
  become: no

- name: Add GCP instance to inventory
  add_host:
    name: "{{instances[0].gce_zone}}-instance"
    ansible_host: "{{ result.networkInterfaces[0].accessConfigs[0].natIP }}"
    ansible_user: runlo
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3






